const KEY="brunoFitnessV1";
const workouts={
Push:[["Supino plano com barra",4,"6–8"],["Supino inclinado com halteres",3,"8–10"],["Chest press",3,"10–12"],["Shoulder press",3,"8–10"],["Elevações laterais",3,"12–15"],["Tríceps na polia",3,"10–12"],["Tríceps acima da cabeça na polia",2,"12–15"]],
Pull:[["Puxada frontal",4,"6–10"],["Remada sentada na polia",3,"8–10"],["Remada apoiada no peito",3,"8–12"],["Puxada unilateral",2,"10–12"],["Reverse fly",3,"12–15"],["Face pull",2,"12–15"],["Curl de bíceps com halteres",3,"8–12"],["Curl martelo",2,"10–12"]],
Legs:[["Agachamento / Hack squat",4,"6–8"],["Leg press",3,"8–12"],["Peso morto romeno",3,"8–10"],["Leg curl",3,"10–12"],["Leg extension",2,"12–15"],["Gémeos",4,"10–15"],["Crunch na polia",3,"10–15"],["Elevação de pernas",3,"10–15"]],
Upper:[["Supino inclinado",3,"6–8"],["Puxada frontal / pull-up assistido",3,"6–10"],["Chest press",3,"8–12"],["Remada máquina",3,"8–12"],["Elevações laterais",3,"12–15"],["Reverse fly",2,"12–15"],["Curl de bíceps",3,"10–12"],["Tríceps na polia",3,"10–12"]],
Lower:[["Hack squat / agachamento",3,"8–10"],["Peso morto romeno",3,"8–10"],["Leg press",3,"10–12"],["Leg curl",3,"10–15"],["Leg extension",2,"12–15"],["Gémeos",4,"12–15"],["Crunch na polia",3,"12–15"],["Prancha",3,"30–60 s"]]};
const meals=[
["Pequeno-almoço","2 Weetabix + 200 g iogurte grego sem lactose + fruta + 25–30 g whey isolate"],
["Almoço","150–180 g frango + 150–180 g arroz cozido + legumes/salada + 10 g azeite + fruta"],
["Pré-treino","Banana + 2–3 tortitas de arroz + 20–25 g whey"],
["Jantar","100–120 g massa cozida + 150 g frango + 1 ovo + salada + 5–10 g azeite"],
["Ceia opcional","Skyr/iogurte sem lactose ou whey + fruta"]];
const initial={weight:88.2,waist:95,water:0,measurements:[],sessions:[],sets:{},mealChecks:{},page:"dashboard",workoutIndex:0};
let state=JSON.parse(localStorage.getItem(KEY)||"null")||initial;
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const today=()=>new Date().toISOString().slice(0,10);
const fmt=n=>Number(n||0).toFixed(1).replace(".",",");
const pages={};

pages.dashboard=()=>{let pct=Math.min(100,Math.max(0,(88.2-state.weight)/8.2*100)),next=Object.keys(workouts)[state.workoutIndex%5];return `<div class="content"><div class="hero"><div class="small">OBJETIVO 6 MESES</div><div style="font-size:30px;font-weight:850;margin:5px 0">80 kg · cintura &lt; 90 cm</div><div class="small">${state.weight>80?`Faltam ${fmt(state.weight-80)} kg.`:"Objetivo de peso atingido."}</div><div class="progress" style="margin-top:15px"><div style="width:${pct}%"></div></div></div><div class="grid"><div class="card"><div class="stat-label">Peso</div><div class="stat">${fmt(state.weight)} kg</div></div><div class="card"><div class="stat-label">Cintura</div><div class="stat">${fmt(state.waist)} cm</div></div><div class="card"><div class="stat-label">Calorias alvo</div><div class="stat">2.200</div></div><div class="card"><div class="stat-label">Proteína alvo</div><div class="stat">175 g</div></div></div><div class="card"><div class="row"><div><b>Próximo treino</b><div class="small">${next}</div></div><button class="btn" id="goTraining">Começar</button></div></div><div class="card"><div class="row"><b>Hidratação</b><span class="pill">${state.water} / 2.500 ml</span></div><div class="progress" style="margin:12px 0"><div style="width:${Math.min(100,state.water/25)}%"></div></div><button class="btn secondary" id="waterBtn">+500 ml</button></div><div class="card"><b>Plano base</b><p class="small">5 dias: Push → Pull → Legs → Upper → Lower. Trabalha em RIR 2 e aumenta a carga quando atingires o topo da faixa com boa técnica.</p></div></div>`};

pages.training=()=>{let type=Object.keys(workouts)[state.workoutIndex%5],html=`<div class="content"><div class="card"><div class="row"><div><b>${type}</b><div class="small">Sessão ${state.workoutIndex%5+1} de 5 · RIR 2</div></div><button class="btn" id="finishWorkout">Terminar</button></div></div>`;workouts[type].forEach((e,i)=>{let key=type+"-"+i,sets=state.sets[key]||Array.from({length:e[1]},()=>({kg:"",reps:"",rir:"2",done:false}));html+=`<div class="exercise"><h3>${i+1}. ${e[0]}</h3><div class="small">${e[1]} séries · ${e[2]} reps</div><div class="sets" style="margin-top:9px"><div>#</div><div>kg</div><div>reps</div><div>RIR</div><div>✓</div>`;sets.forEach((s,j)=>html+=`<div>${j+1}</div><input data-set="${type}|${i}|${j}|kg" value="${s.kg||""}" inputmode="decimal"><input data-set="${type}|${i}|${j}|reps" value="${s.reps||""}" inputmode="numeric"><input data-set="${type}|${i}|${j}|rir" value="${s.rir||"2"}" inputmode="numeric"><input type="checkbox" data-set="${type}|${i}|${j}|done" ${s.done?"checked":""}>`);html+="</div></div>"});return html+"</div>"};

pages.nutrition=()=>`<div class="content"><div class="card"><div class="row"><b>Meta diária</b><span class="pill">2.200 kcal</span></div><div class="grid" style="margin-top:12px"><div><b>175 g</b><div class="small">Proteína</div></div><div><b>65 g</b><div class="small">Gordura</div></div><div><b>215 g</b><div class="small">Hidratos</div></div><div><b>${meals.filter((_,i)=>state.mealChecks[today()+"-"+i]).length}/5</b><div class="small">Refeições</div></div></div></div><div class="card"><b>Plano diário</b>${meals.map((m,i)=>`<div class="meal"><div><b>${m[0]}</b><div class="small">${m[1]}</div></div><input class="mealcheck" type="checkbox" data-meal="${i}" ${state.mealChecks[today()+"-"+i]?"checked":""}></div>`).join("")}</div><div class="card"><div class="row"><b>Água</b><span>${state.water} ml</span></div><button class="btn" style="margin-top:10px" id="waterBtn2">+500 ml</button></div><div class="notice">Privilegia versões sem lactose e whey isolate sempre que necessário.</div></div>`;

pages.body=()=>`<div class="content"><div class="card"><b>Registar medição</b><div class="grid" style="margin-top:12px"><div class="field"><label>Peso (kg)</label><input id="weightInput" type="number" step=".1" value="${state.weight}"></div><div class="field"><label>Cintura (cm)</label><input id="waistInput" type="number" step=".1" value="${state.waist}"></div><div class="field"><label>Peito</label><input id="chestInput" type="number" step=".1"></div><div class="field"><label>Braço</label><input id="armInput" type="number" step=".1"></div><div class="field"><label>Coxa</label><input id="thighInput" type="number" step=".1"></div></div><button class="btn" id="saveMeasurement">Guardar hoje</button></div><div class="card"><b>Histórico</b>${state.measurements.length?state.measurements.slice().reverse().map(x=>`<div class="row" style="padding:10px 0;border-bottom:1px solid #eee"><span>${x.date}</span><span><b>${fmt(x.weight)} kg</b> · ${fmt(x.waist)} cm</span></div>`).join(""):"<div class='empty'>Ainda não tens medições.</div>"}</div></div>`;

pages.progress=()=>{let arr=state.measurements.slice(-10),min=Math.min(...arr.map(x=>x.weight),80),max=Math.max(...arr.map(x=>x.weight),88.2),range=Math.max(1,max-min);return `<div class="content"><div class="card"><b>Evolução do peso</b>${arr.length?`<div class="bar-chart">${arr.map(x=>`<div class="bar" style="height:${Math.max(5,(x.weight-min)/range*100)}%"><span>${fmt(x.weight)}</span></div>`).join("")}</div>`:"<div class='empty'>Regista medições para veres a evolução.</div>"}</div><div class="grid"><div class="card"><div class="stat-label">Objetivo</div><div class="stat">80 kg</div></div><div class="card"><div class="stat-label">Cintura</div><div class="stat">&lt;90 cm</div></div></div><div class="card"><b>Progressão</b><p class="small">Ao atingir o topo da faixa em todas as séries com boa técnica, aumenta ligeiramente a carga. Se peso e cintura não mudarem por 2 semanas, reduz 100–150 kcal ou aumenta os passos.</p></div></div>`};

function render(){document.querySelectorAll(".tabbar button").forEach(b=>b.classList.toggle("active",b.dataset.page===state.page));document.getElementById("pageTitle").textContent={dashboard:"Dashboard",training:"Treino",nutrition:"Nutrição",body:"Corpo",progress:"Progresso"}[state.page];document.getElementById("main").innerHTML=pages[state.page]();bind()}
function bind(){
document.querySelectorAll(".tabbar button").forEach(b=>b.onclick=()=>{state.page=b.dataset.page;save();render()});
const g=id=>document.getElementById(id);
if(g("goTraining"))g("goTraining").onclick=()=>{state.page="training";save();render()};
["waterBtn","waterBtn2"].forEach(id=>{if(g(id))g(id).onclick=()=>{state.water+=500;save();render()}});
if(g("finishWorkout"))g("finishWorkout").onclick=()=>{state.sessions.push({date:today(),type:Object.keys(workouts)[state.workoutIndex%5]});state.workoutIndex++;save();render()};
document.querySelectorAll("[data-set]").forEach(el=>el.onchange=()=>{let[a,i,j,k]=el.dataset.set,key=a+"-"+i;state.sets[key] ||= Array.from({length:workouts[a][i][1]},()=>({}));state.sets[key][j][k]=el.type==="checkbox"?el.checked:el.value;save()});
document.querySelectorAll(".mealcheck").forEach(el=>el.onchange=()=>{state.mealChecks[today()+"-"+el.dataset.meal]=el.checked;save();render()});
if(g("saveMeasurement"))g("saveMeasurement").onclick=()=>{let w=+g("weightInput").value,wa=+g("waistInput").value;if(!w||!wa)return alert("Preenche peso e cintura.");state.weight=w;state.waist=wa;state.measurements.push({date:today(),weight:w,waist:wa,chest:+g("chestInput").value||null,arm:+g("armInput").value||null,thigh:+g("thighInput").value||null});save();render()};
}
document.getElementById("resetBtn").onclick=()=>{if(confirm("Apagar todos os dados?")){localStorage.removeItem(KEY);state=JSON.parse(JSON.stringify(initial));render()}};
if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));render();